theme: jekyll-theme-cayman
title: About Me
author: Alyssa Wu
description: > # this means to ignore newlines until "baseurl:"
  This website contains information about me and my achievements throughout high school.

# social links
twitter_username: awu4 # DO NOT include the @ character, or else the build will fail!
github_username: arysha # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
